# Server settings
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    min-spare-threads: 30
  max-http-header-size: 102400


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: root
    hikari:
      connection-test-query: select 1

# MyBatis
mybatis:
  typeAliasesPackage: com.ure
  mapperLocations: classpath:mybatis/**/*Mapper.xml
  configLocation: classpath:mybatis/mybatis-config.xml

# 日志配置
logging:
  level:
    org.apache.ibatis: DEBUG

ureport.mysql.provider:
  prefix: ureport-
  disabled: false




